services:
  app:
    image: lovelost/parser
    restart: always
    expose:
      - 8080
    networks:
      - backend

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    networks:
      - backend

  # adminer:
  #   image: adminer
  #   restart: always
  #   expose:
  #     - 8080
  #   networks:
  #     - backend

  nginx:
    image: anroe/nginx-geoip2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./geolite-db/GeoLite2-Country.mmdb:/etc/nginx/GeoLite2-Country.mmdb
    depends_on:
      - app
      # - adminer
    networks:
      - backend

networks:
  backend:
    driver: bridge