FROM nginx:latest

RUN apt-get update && apt-get install -y libmaxminddb-dev

# Скачиваем исходники nginx и модуль GeoIP2
RUN cd /tmp && \
    wget http://nginx.org/download/nginx-$(nginx -v 2>&1 | awk -F'/' '{print $2}').tar.gz && \
    tar -xzvf nginx-*.tar.gz && \
    git clone https://github.com/leev/ngx_http_geoip2_module.git

# Пересобираем nginx с модулем
RUN cd /tmp/nginx-* && \
    ./configure --with-compat --add-module=/tmp/ngx_http_geoip2_module && \
    make && make install

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY GeoLite2-Country.mmdb /etc/nginx/GeoLite2-Country.mmdb