FROM python:3.12
WORKDIR /usr/local/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./src
EXPOSE 8080

RUN useradd app
USER app

CMD ["uvicorn", "main:app", "--host", "::", "--port", "8080", "--app-dir=./src"]