services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.ipv4
    restart: always
    expose:
      - 8080
    networks:
      - backend_ipv4

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    # command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - backend_ipv4

  # adminer:
  #   image: adminer
  #   restart: always
  #   expose:
  #     - 8080
  #   networks:
  #     - backend_ipv4

  nginx:
    image: anroe/nginx-geoip2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx_ipv4.conf:/etc/nginx/nginx.conf
      - ./geolite-db/GeoLite2-Country.mmdb:/etc/nginx/GeoLite2-Country.mmdb
    depends_on:
      - app
      # - adminer
    networks:
      - backend_ipv4

networks:
  backend_ipv4:
    driver: bridge