load_module modules/ngx_http_geoip2_module.so;

events {
    worker_connections 1024;
}

http {
    geoip2 /etc/nginx/GeoLite2-Country.mmdb {
        $geoip2_data_country_code country iso_code;
    }

    map $geoip2_data_country_code $allowed_country {
        default 1;
        RU 0;
    }

    # geo $blocked_ip {
    #     default 0;
    #     192.168.0.117 1;
    # }

    server {
        listen 80;

        location / {
            # if ($blocked_ip = 1) {
            #     return 403 "Access denied for your IP address";
            # }

            if ($allowed_country = 0) {
                return 403 "Access denied for your region";
            }

            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # location /adminer/ {
        #     if ($blocked_ip = 1) {
        #         return 403 "Access denied for your IP address";
        #     }
        #     
        #     if ($allowed_country = 0) {
        #         return 403 "Access denied for your region";
        #     }
        #     
        #     proxy_pass http://adminer:8080/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # }
    }
}